### PR TITLE
Replace axios with native fetch

### PR DESCRIPTION
**Pull request by mattt**
Related to https://github.com/replicate/replicate-javascript/pull/29#issuecomment-1489371435

> The decision to use axios was entirely pragmatic — it was the first thing I got working, so I went with that. I'd be very open to dropping it entirely for fetch if that works cross-platform reasonably well.

This PR should do exactly that. I'm out of the loop about preferred `fetch` polyfill libraries and other packaging concerns, so if you have any strong opinions, please let me know!

### CODE REVIEW

**Comment by nfcampos** [comment]
Wonderful, this is much better. 

What versions of node are you targeting?

the ideal way to use fetch is to 1. accept it as an argument (for unit tests) but default to looking for a global fetch function, which is now available in node 18+ and all other JS envs

**Comment by zeke** [comment]
> What versions of node are you targeting?

We don't have a documented policy, but [LTS (currently >=18)](https://github.com/nodejs/release#release-schedule)) seems sensible.

**Comment by nfcampos** [comment]
Great, then there is no reason to use cross-fetch, as fetch is available globally in node 18+ without a flag

**Comment by danielrhodes** [comment]
This is great. Was going to fork this library to use inside a Cloudflare Worker.

**Pull request merged**
